# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/test/integration_test" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/v1/cmd/server/build/" # Location of package manifests
    schedule:
      interval: "monthly"