run:
  concurrency: 4
  tests: true
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - gocritic
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - mirror
    - nilerr
    - predeclared
    - revive
    - unconvert
linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - assignOp
      - ifElseChain
  revive:
    rules:
      - name: unused-parameter
        disabled: true
issues:
  exclude-use-default: false
  exclude-rules:
    - path: third_party
      linters:
        - all
    - path: builtin
      linters:
        - all
    - path: examples
      linters:
        - all
