# Options for analysis running.
run:
  concurrency: 2
  timeout: 10m
  tests: true
  skip-dirs:
    - gen
    - service-client
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - predeclared
    - errorlint
    - unparam 