version: '3.9'
x-custom:
  omnistrate-mode-internal:
    - true
    - false
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - ./data:/var/lib/postgresql/data
    x-omnistrate-mode-internal: true
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    volumes:
      - ./ferretdb:/state
    depends_on:
      - postgres
    ports:
      - '27017:27017'
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb
