version: '3.9'
x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics
services:
  Postgres:
    image: postgres
    ports:
      - '5432:5432'
    x-omnistrate-api-params:
      - key: password
        description: Postgres user password
        name: Password
        type: String
        modifiable: true
        required: true
        export: false
        defaultValue: a_secure_password
      - key: username
        description: Postgres user name
        name: Username
        type: String
        modifiable: true
        required: true
        export: true
        defaultValue: username
    environment:
      - SECURITY_CONTEXT_USER_ID=999
      - SECURITY_CONTEXT_GROUP_ID=999
      - POSTGRES_USER=$var.username
      - POSTGRES_PASSWORD=$var.password
      - PGDATA=/var/lib/postgresql/data/dbdata
    volumes:
      - source: ./data
        target: /var/lib/postgresql/data
        type: bind
        x-omnistrate-storage:
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 100
            instanceStorageIOPS: 3000
            instanceStorageThroughputMiBps: 125
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 100
