version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    x-omnistrate-capabilities:
      autoscaling:
        maxReplicas: 1
        minReplicas: 1
      serverlessConfiguration:
        enableAutoStop: true
        minimumNodesInPool: 1
        targetPort: 6379