# Logo: https://images.crunchbase.com/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/wdokbxqenwwry7hffgkg
version: "3"
networks:
  redpanda_network:
    driver: bridge
x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics
services:
  redpanda:
    image: "ghcr.io/omnistrate/demos-redpanda:v23.2.9-core"
    ports:
      - "9092:9092"
      - "8082:8082"
      - "8081:8081"
      - "9644:9644"
    x-omnistrate-mode-internal: false
    x-omnistrate-compute:
      replicaCountAPIParam: numNodes
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
        - cloudProvider: gcp
          apiParam: instanceType
    x-omnistrate-capabilities:
      enableMultiZone: true
      enableEndpointPerReplica: true
#    x-omnistrate-actionhooks:
#     - scope: CLUSTER
#       type: INIT
#       commandTemplate: |
#         # Fail on any error
#         set -ex
#
#         # Enable SASL
#         rpk cluster config set enable_sasl true \
#           -X admin.hosts=${RESOURCE_ALIAS}-0:9644 \
#           -X brokers=${RESOURCE_ALIAS}-0:29092
#
#         # Enable auth
#         rpk cluster config set kafka_enable_authorization true \
#           -X admin.hosts=${RESOURCE_ALIAS}-0:9644 \
#           -X brokers=${RESOURCE_ALIAS}-0:29092
#
#         # Set the superuser name
#         rpk cluster config set superusers ['{{ $var.adminUsername }}'] \
#           -X admin.hosts=${RESOURCE_ALIAS}-0:9644 \
#           -X brokers=${RESOURCE_ALIAS}-0:29092
#
#         # Create the superuser
#         rpk acl user create {{ $var.adminUsername }} -p '{{ $var.adminPassword }}' \
#           -X admin.hosts=${RESOURCE_ALIAS}-0:9644 \
#           -X brokers=${RESOURCE_ALIAS}-0:29092

    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
        defaultValue: t4g.small
      - key: numNodes
        description: Number of Nodes
        name: Number of Nodes
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "1"
    environment:
      SECURITY_CONTEXT_USER_ID: "0"
      SECURITY_CONTEXT_GROUP_ID: "0"
      SECURITY_CONTEXT_FS_GROUP: "0"
    volumes:
      - ./data:/var/lib/redpanda/data
    networks:
      - redpanda_network