version: '3.8'

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

services:
  Agent:
    image: omnistrate/warpstream-arm64:v2
    ports:
      - 9092:9092
    volumes:
    - type: cluster
      x-omnistrate-storage:
        aws:
          clusterStorageType: AWS::S3
    x-omnistrate-compute:
      instanceTypes:
        - apiParam: agentInstanceType
          cloudProvider: aws
        - apiParam: agentInstanceType
          cloudProvider: gcp
    x-omnistrate-capabilities:
      autoscaling:
        minReplicas: 1
        maxReplicas: 10
      enableMultiZone: true
    environment:
      - WARPSTREAM_BUCKET_URL=s3://$(INSTANCE_ID)-$(RESOURCE_ALIAS)-bucket?region=$(AWS_REGION)
      - WARPSTREAM_API_KEY=$var.warpstreamApiKey
      - WARPSTREAM_DEFAULT_VIRTUAL_CLUSTER_ID=$var.virtualClusterId
      - WARPSTREAM_AGENT_POOL_NAME=$var.warpstreamAgentPoolName
      - WARPSTREAM_DISCOVERY_KAFKA_HOSTNAME_OVERRIDE={{ $sys.network.node.externalEndpoint }}
    x-omnistrate-mode-internal: false
    x-omnistrate-api-params:
      - key: agentInstanceType
        description: Instance Type for the Agent service
        name: Agent Instance Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: warpstreamApiKey
        description: API Key for Warpstream
        name: Warpstream API Key
        type: String
        modifiable: true
        required: true
        export: false
      - key: virtualClusterId
        description: Default Virtual Cluster ID for Warpstream
        name: Virtual Cluster ID
        type: String
        modifiable: false
        required: true
        export: true
      - key: warpstreamAgentPoolName
        description: Agent Pool Name for the custom Virtual Cluster
        name: Agent Pool Name
        type: String
        modifiable: false
        required: true
        export: true