name: Build documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd mkdocs
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          cd mkdocs
          mkdocs build --strict
          echo "Documentation build completed successfully!"
          echo "The --strict flag ensures that warnings are treated as errors."
          echo "All links, paths, and files have been validated during the build process."
