name: Package

on:
  push:
    paths:
    - build/Dockerfile
    branches: 
    - master
  pull_request:
    paths:
      - build/Dockerfile
    branches: 
    - master
  release:
    types: [ "published" ]

env:
  GOPRIVATE: github.com/omnistrate
  GOPROXY: ${{ secrets.GOPROXY }}
  GOSUMDB: ${{ secrets.GOSUMDB }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # platforms to build the image for
  PLATFORMS: linux/arm64,linux/amd64  
  # default platform of the runners, used to mitigate time of building on x arch during PRs
  PR_PLATFORMS: linux/amd64
  # name of the package 
  PACKAGE_NAME: omnistrate-ctl
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  package:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read

    concurrency:
      group: package-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
       
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.CI_APP_ID }}
          private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          platforms: ${{ env.PLATFORMS }}
          
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |         
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long

      - name: Build on ${{ env.PR_PLATFORMS }} only
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile
          platforms: ${{ env.PR_PLATFORMS }}
          build-args: |
              GIT_USER=api 
              GIT_TOKEN=${{ steps.generate_token.outputs.token }}
              GOPROXY=${{ secrets.GOPROXY }}
              GOSUMDB=${{ secrets.GOSUMDB }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  package-multi-arch:
    runs-on: ubicloud-standard-8
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    concurrency:
      group: package-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
       
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.CI_APP_ID }}
          private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name == 'release'
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          platforms: ${{ env.PLATFORMS }}
          
      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |         
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long

      # https://github.com/docker/build-push-action
      - name: Build and push multi-arch
        timeout-minutes: 20
        if: github.event_name != 'pull_request'
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          build-args: |
              GIT_USER=api 
              GIT_TOKEN=${{ steps.generate_token.outputs.token }}
              GOPROXY=${{ secrets.GOPROXY }}
              GOSUMDB=${{ secrets.GOSUMDB }}
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      # Sign the resulting Docker image digest except on PRs.
      # https://github.com/sigstore/cosign
      - name: Sign the images with GitHub OIDC Token **not production ready**
        if: github.event_name == 'release'
        run: cosign sign --yes ${TAGS}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
