name: Release

on:
  release:
    types: [ "published" ]
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  GOPRIVATE: "github.com/omnistrate/*"
  GOPROXY: ${{ secrets.GOPROXY }}
  GOSUMDB: ${{ secrets.GOSUMDB }}
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@v4

      - name: Generate token
        timeout-minutes: 5
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.CI_APP_ID }}
          private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: Configure git for private repo access
        timeout-minutes: 5
        env:
          GH_ACCESS_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "machine github.com login api password ${GH_ACCESS_TOKEN}" > ~/.netrc

      - name: Set up go
        timeout-minutes: 10
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          token: ${{ steps.generate_token.outputs.token }}
          cache-dependency-path: '**/go.sum'

      - name: Get dependencies
        timeout-minutes: 10
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make tidy

      - name: Build
        timeout-minutes: 20
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
      
      - name: Calculate binary name
        timeout-minutes: 1
        id: calc_binary_name
        run: |
          binary_name="omnistrate-ctl-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            binary_name="${binary_name}.exe"
          fi
          echo "binary_name=$binary_name" >> "$GITHUB_OUTPUT"

      - name: Upload build artifacts
        timeout-minutes: 5
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.calc_binary_name.outputs.binary_name }}
          path: dist/${{ steps.calc_binary_name.outputs.binary_name }}

  sanity-check:
    needs: build
    permissions:
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubicloud-standard-2-arm]
    
    runs-on: ${{ matrix.os }}

    steps: 
      - name: Download build artifacts
        timeout-minutes: 5
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        timeout-minutes: 1
        run: ls -R
          
      - name: Run the binary (linux and macos only)
        id: run_binary_linux_macos
        timeout-minutes: 1
        if: matrix.os != 'windows-latest'
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            export GOOS=darwin
            export GOARCH=arm64
          elif [ "${{ matrix.os }}" == "ubic-cloud-standard-2-arm" ]; then
            export GOOS=linux
            export GOARCH=arm64
          else
            export GOOS=linux
            export GOARCH=amd64
          fi

          binary_name="omnistrate-ctl-${GOOS}-${GOARCH}"
          cd $binary_name
          chmod +x $binary_name
          ctl_version=$(./$binary_name --version)
          echo "Version: $ctl_version"
          echo "ctl_version=$ctl_version" >> "$GITHUB_OUTPUT"

      - name: Run the binary (windows only)
        id: run_binary_windows
        timeout-minutes: 1
        if: matrix.os == 'windows-latest'
        run: |
          cd omnistrate-ctl-windows-amd64
          $ctl_version=omnistrate-ctl-windows-amd64.exe --version
          echo "Version: $ctl_version"
          echo "ctl_version=$ctl_version" >> $env:GITHUB_OUTPUT
    
  release:
    runs-on: ubuntu-latest
    needs: sanity-check
    permissions:
      contents: read

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps: 
      - name: Calculate binary name
        timeout-minutes: 1
        id: calc_binary_name
        run: |
          binary_name="omnistrate-ctl-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            binary_name="${binary_name}.exe"
          fi
          echo "binary_name=$binary_name" >> "$GITHUB_OUTPUT"

      - name: Download build artifacts
        timeout-minutes: 5
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        timeout-minutes: 1
        run: ls -R
          
      - name: Generate token to create the release
        timeout-minutes: 5
        id: generate_token_cli
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.CLI_APP_ID }}
          private_key: ${{ secrets.CLI_APP_PRIVATE_KEY }}

      - name: Upload binaries on a new release
        timeout-minutes: 5
        uses: softprops/action-gh-release@v1
        with:
            files: | 
              ${{ steps.calc_binary_name.outputs.binary_name }}/${{ steps.calc_binary_name.outputs.binary_name }}
            repository: omnistrate/cli
            token: ${{ steps.generate_token_cli.outputs.token }}
            fail_on_unmatched_files: true
            draft: true
