name: Test Install Script

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "install-ctl.sh"
      - ".github/workflows/test-install-script.yml"
  
jobs:
  test-install-script:
    runs-on: ${{ matrix.os }}
    permissions: {}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]

    steps:
      - name: Test curl installation
        timeout-minutes: 10
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          # Test the exact curl command from the documentation
          # This simulates what users will actually run
          curl -fsSL https://raw.githubusercontent.com/omnistrate-oss/ctl/main/install-ctl.sh | sh

          # Add omnistrate-ctl to PATH and get version
          export PATH="$HOME/.omnistrate/bin:$PATH"
          ctl_version=$(omnistrate-ctl --version)
          echo "Omnistrate CTL version: $ctl_version"
          echo "ctl_version=$ctl_version" >> "$GITHUB_OUTPUT"

      - name: Test curl installation (Windows)
        timeout-minutes: 10
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          # Test the exact curl command from the documentation
          # This simulates what users will actually run
          curl -fsSL https://raw.githubusercontent.com/omnistrate-oss/ctl/main/install-ctl.sh | sh

          # Add omnistrate-ctl to PATH and get version
          export PATH="$HOME/.omnistrate/bin:$PATH"
          ctl_version=$(omnistrate-ctl.exe --version)
          echo "Omnistrate CTL version: $ctl_version"
          echo "ctl_version=$ctl_version" >> "$GITHUB_OUTPUT"

