site_name: " " 
site_url: https://ctl.omnistrate.cloud/
site_description: >-
  Omnistrate CTL Manual

# TODO 0.0.0.0

theme:
  logo: assets/logo.png
  name: material
  favicon: images/favicon.png
  features:
    #- navigation.tabs
    #- navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
   # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: lime  

validation:
  absolute_links: ignore

nav:
  - Docs homepage: 'https://docs.omnistrate.com/'
  - Install omnistrate-ctl: 'install.md'
  - Integrate with omnistrate-ctl: "integrating.md"
  - Commands:
    - omnistrate-ctl account: 'omnistrate-ctl_account.md'
    - omnistrate-ctl build: 'omnistrate-ctl_build.md'
    - omnistrate-ctl describe: 'omnistrate-ctl_describe.md'
    - omnistrate-ctl domain: 'omnistrate-ctl_domain.md'
    - omnistrate-ctl helm: 'omnistrate-ctl_helm.md'
    - omnistrate-ctl instance: 'omnistrate-ctl_instance.md'
    - omnistrate-ctl list: 'omnistrate-ctl_list.md'
    - omnistrate-ctl login: 'omnistrate-ctl_login.md'
    - omnistrate-ctl logout: 'omnistrate-ctl_logout.md'
    - omnistrate-ctl remove: 'omnistrate-ctl_remove.md'
    - omnistrate-ctl service: 'omnistrate-ctl_service.md'
    - omnistrate-ctl service-plan: 'omnistrate-ctl_service-plan.md'
    - omnistrate-ctl subscription: 'omnistrate-ctl_subscription.md'
    - omnistrate-ctl upgrade: 'omnistrate-ctl_upgrade.md'

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://docs.omnistrate.com/
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/omnistrate
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/omnistrate
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/omnistrate/about/
  analytics:
    provider: google
    property: G-2VH2LJR946

extra_javascript:
  # - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox
  - include_dir_to_nav
  - search

copyright: |
  &copy; 2023 Omnistrate.Inc All rights reserved.
