site_name: " "
site_url: https://ctl.omnistrate.cloud/
site_description: >-
  Omnistrate CTL Manual
repo_url: https://github.com/omnistrate-oss/omnistrate-ctl
repo_name: omnistrate-oss/omnistrate-ctl

# TODO 0.0.0.0

theme:
  logo: assets/logo.png
  name: material
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    #- navigation.tabs
    #- navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: lime

validation:
  absolute_links: ignore

nav:
  - Install CTL: "install.md"
  - Integrate CTL: "integrating.md"
  - CTL Usage: "omnistrate-ctl.md"
  - Commands:
      - login: "omnistrate-ctl_login.md"
      - logout: "omnistrate-ctl_logout.md"
      - account: "omnistrate-ctl_account.md"
      - build: "omnistrate-ctl_build.md"
      - build-from-repo: "omnistrate-ctl_build-from-repo.md"
      - custom-network: "omnistrate-ctl_custom-network.md"
      - domain: "omnistrate-ctl_domain.md"
      - environment: "omnistrate-ctl_environment.md"
      - helm: "omnistrate-ctl_helm.md"
      - inspect: "omnistrate-ctl_inspect.md"
      - instance: "omnistrate-ctl_instance.md"
      - secret: "omnistrate-ctl_secret.md"
      - service: "omnistrate-ctl_service.md"
      - services-orchestration: "omnistrate-ctl_services-orchestration.md"
      - service-plan: "omnistrate-ctl_service-plan.md"
      - subscription: "omnistrate-ctl_subscription.md"
      - upgrade: "omnistrate-ctl_upgrade.md"

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://docs.omnistrate.com/
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/omnistrate/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/omnistrate/
    - icon: fontawesome/brands/github
      link: https://github.com/omnistrate-oss/omnistrate-ctl
  analytics:
    provider: google
    property: G-2VH2LJR946
extra_javascript:
  # - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox
  - include_dir_to_nav
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

copyright: |
  &copy; 2023 Omnistrate.Inc All rights reserved.
