site_name: " " 
site_url: https://ctl.omnistrate.cloud/
site_description: >-
  Omnistrate CTL Manual

# TODO 0.0.0.0

theme:
  logo: assets/logo.png
  name: material
  favicon: images/favicon.png
  features:
    #- navigation.tabs
    #- navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
   # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: lime  

validation:
  absolute_links: ignore

nav:
  - Install CTL: 'install.md'
  - Integrate CTL: "integrating.md"
  - Commands:
      - account:
          - title: 'account'
            link: 'omnistrate-ctl_account.md'
          - create: 'omnistrate-ctl_account_create.md'
          - list: 'omnistrate-ctl_account_list.md'
          - describe: 'omnistrate-ctl_account_describe.md'
          - delete: 'omnistrate-ctl_account_delete.md'
      - auth:
          - login: 'omnistrate-ctl_auth_login.md'
          - logout: 'omnistrate-ctl_auth_logout.md'
      - build: 'omnistrate-ctl_build.md'
      - domain:
          - title: 'domain'
            link: 'omnistrate-ctl_domain.md'
          - create: 'omnistrate-ctl_domain_create.md'
          - list: 'omnistrate-ctl_domain_list.md'
          - describe: 'omnistrate-ctl_domain_describe.md'
          - delete: 'omnistrate-ctl_domain_delete.md'
      - helm:
          - title: 'helm'
            link: 'omnistrate-ctl_helm.md'
          - save: 'omnistrate-ctl_helm_save.md'
          - list: 'omnistrate-ctl_helm_list.md'
          - list-installations: 'omnistrate-ctl_helm_list-installations.md'
          - describe: 'omnistrate-ctl_helm_describe.md'
          - delete: 'omnistrate-ctl_helm_delete.md'
      - instance:
          - title: 'instance'
            link: 'omnistrate-ctl_instance.md'
          - create: 'omnistrate-ctl_instance_create.md'
          - list: 'omnistrate-ctl_instance_list.md'
          - describe: 'omnistrate-ctl_instance_describe.md'
          - delete: 'omnistrate-ctl_instance_delete.md'
      - service:
          - title: 'service'
            link: 'omnistrate-ctl_service.md'
          - delete: 'omnistrate-ctl_service_delete.md'
          - list: 'omnistrate-ctl_service_list.md'
          - describe: 'omnistrate-ctl_service_describe.md'
      - service-plan:
          - title: 'service-plan'
            link: 'omnistrate-ctl_service-plan.md'
          - list: 'omnistrate-ctl_service-plan_list.md'
          - describe: 'omnistrate-ctl_service-plan_describe.md'
          - list-versions: 'omnistrate-ctl_service-plan_list-versions.md'
          - describe-version: 'omnistrate-ctl_service-plan_describe-version.md'
          - delete: 'omnistrate-ctl_service-plan_delete.md'
          - release: 'omnistrate-ctl_service-plan_release.md'
          - set-default: 'omnistrate-ctl_service-plan_set-default.md'
      - subscription:
          - title: 'subscription'
            link: 'omnistrate-ctl_subscription.md'
          - list: 'omnistrate-ctl_subscription_list.md'
          - describe: 'omnistrate-ctl_subscription_describe.md'
      - upgrade:
          - title: 'upgrade'
            link: 'omnistrate-ctl_upgrade.md'
          - status: 'omnistrate-ctl_upgrade_status.md'
          - status detail: 'omnistrate-ctl_upgrade_status-detail.md'

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://docs.omnistrate.com/
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/omnistrate
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/omnistrate
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/omnistrate/about/
  analytics:
    provider: google
    property: G-2VH2LJR946

extra_javascript:
  # - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox
  - include_dir_to_nav
  - search

copyright: |
  &copy; 2023 Omnistrate.Inc All rights reserved.
